export const CHANGE_CURRENT_BEHANDELING = 'CHANGE_CURRENT_BEHANDELING';
export const CHANGE_CURRENT_MEDICIJN = 'CHANGE_CURRENT_MEDICIJN';
export const TOGGLE_TODO = 'TOGGLE_TODO';
export const ADD_NOTE = 'ADD_NOTE';
export const FETCH_PATIENT = 'FETCH_PATIENT';
export const CHECK_TOKEN = 'CHECK_TOKEN';
export const TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING';
export const FETCH_TOKEN = 'FETCH_TOKEN';
